server:
  port: 8761

spring:
  application:
    name: eureka-server
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    fetch-registry: false
    register-with-eureka: false

# Actuator Prometheus Endpoint
management:
  endpoints:
    web:
      exposure:
        include: prometheus

## Jaeger config
#opentracing:
#  jaeger:
#    enabled: true
#    log-spans: true
#    const-sampler:
#      decision: true
#    udp-sender:
#      host: localhost
#      port: 6831
